### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by rajasagashe** [kinspire/kinspire-portal#11]
What do I need to setup to get the login page to work? This is the message I get when I press the login button.

 /login/login.php - Uncaught PDOException: could not find driver in kinspire-portal/app/www/var/pdo.php:10
  thrown in kinspire-portal/app/www/var/pdo.php on line 10

So far I've just been commenting out the redirect to the login page in logincheck.php in order to develop the  achievements page.

**Comment by sarangjo** [comment]
Hmm, this is weird, let me take a look and try to figure it out.

**Comment by sarangjo** [comment]
@rajasagashe I think this should be fixed, can you try pulling the latest changes and logging in with "testaccount" as the username?

**Comment by sarangjo** [comment]
Okay it looks like this might be a problem with your php.ini file, if the PDO driver for SQLite hasn't been added as a dependency.
