### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by sarangjo** [kinspire/kinspire-portal#5]
- [x] Make sure menu position stays same after clicking
- [x] Move home  to be the first on the list (even though in the design it was diff, I know)
- [ ] ~~Increase the font size of all the content text, title is fine, increase content text by 4 pts~~
- [x] Put all four boxes in the resources tab in a box
- [x] the vocab page says errors all over it (just letting you know)
- [ ] also for contact us, you should be able to click and send in any reports to the board (that is different than the volunteer's page)
- [x] Decrease line thickness on the menu and increase font size by 4 in menu
- [x] add in all graphics that are on google dirve
- [ ] make the contact us text match the color of the grey lines
- [x] put "contact us:" and "kinspire@uw.edu" on the same line
- [x] for now cap the boxes, I will send you some better graphics for the boxes, for now try curved edges because the sharp corners don't fit in
- [x] change the color of the blue banner and the orange boxes on the resources page to match the blue and the orange on the website
- [ ] put the word "menu" above the owl and make it same color as owl (both for default and active)
- [ ] center the date below the text "today's date" on the home page
- [ ] center all the light green text
- [ ] otherwise it looks odd since there is nothing more
- [ ] also increase the "type here..." font size by 4 points and make the boxes bigger too, the whole thing should fit in the whole page

**Comment by mteshmore** [comment]
When the menu opens, its height should fill up 3/4 of the website. The boxes after you enter stories aren't aligned. Volunteer Access looks great (except the graphics).

**Comment by mteshmore** [comment]
The site is coming along, looks good!
